_target_: pytorch_lightning.Trainer

gpus: 0
#accelerator: "gpu"

min_epochs: 1
max_epochs: 35

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
#resume_from_checkpoint: /cluster/52/boisbb/project/logs/experiments/runs/training/2022-07-26_15-32-58/checkpoints/epoch_017.ckpt
#overfit_batches: 1
